/**
 * Persona Configuration System
 * Defines all personas, their attributes, features, and preferences
 * 
 * Data source: /data/project-recommendations.json (personas section)
 * Generated by: buildright-aco/scripts/generate-eds-data.js
 */

/**
 * Customer Group Constants
 * Maps to Adobe Commerce customer groups and ACO price books
 */
export const CUSTOMER_GROUPS = {
  US_RETAIL: 'US-Retail',
  PRODUCTION_BUILDER: 'Production-Builder',
  TRADE_PROFESSIONAL: 'Trade-Professional',
  WHOLESALE_RESELLER: 'Wholesale-Reseller',
  RETAIL_REGISTERED: 'Retail-Registered'
};

/**
 * Persona Definitions
 * Each persona represents a distinct user type with unique needs
 */
export const PERSONAS = {
  SARAH: {
    id: 'sarah',
    name: 'Sarah Martinez',
    role: 'Production Builder',
    title: 'Production Builder',
    company: 'Sunbelt Homes',
    description: 'Managing 12 spec homes per year',
    email: 'sarah.martinez@sunbelthomes.com',
    customerGroup: CUSTOMER_GROUPS.PRODUCTION_BUILDER,
    avatar: '/images/avatars/sarah.jpg',
    defaultRoute: '/pages/dashboard.html?view=templates',
    
    // ACO attributes (for policy filtering)
    attributes: {
      construction_phase: 'foundation_framing',
      customer_tier: 'Production-Builder',
      business_type: 'production_builder',
      project_scale: 'high_volume',
      primary_service: 'residential_construction',
      buying_behavior: 'repeat_orders'
    },
    
    // Feature flags
    features: {
      templates: true,
      bomGeneration: true,
      phaseOrdering: true,
      repeatOrdering: true,
      projectWizard: false,
      packageBuilder: false,
      deckBuilder: false,
      restockDashboard: false
    },
    
    // UI preferences
    preferences: {
      defaultView: 'templates',
      showFloorPlans: true,
      showAnalytics: true,
      showEducationalContent: false,
      guidedMode: false,
      showVisuals: false,
      comparePackages: false,
      showVelocity: false,
      priorityIndicators: false
    }
  },
  
  MARCUS: {
    id: 'marcus',
    name: 'Marcus Johnson',
    role: 'General Contractor',
    title: 'General Contractor',
    company: 'Johnson Construction',
    description: 'Custom homes and major renovations',
    email: 'marcus.johnson@johnsonconstruction.com',
    customerGroup: CUSTOMER_GROUPS.TRADE_PROFESSIONAL,
    avatar: '/images/avatars/marcus.jpg',
    defaultRoute: '/pages/builder.html?type=project',
    
    attributes: {
      construction_phase: 'foundation_framing',
      quality_tier: 'professional',
      customer_tier: 'Trade-Professional',
      business_type: 'general_contractor',
      project_scale: 'medium_volume',
      primary_service: 'residential_construction',
      buying_behavior: 'project_based'
    },
    
    features: {
      templates: false,
      bomGeneration: true,
      phaseOrdering: true,
      repeatOrdering: false,
      projectWizard: true,
      phaseSelection: true,
      qualityTiers: true,
      packageBuilder: false,
      deckBuilder: false,
      restockDashboard: false
    },
    
    preferences: {
      defaultView: 'projects',
      showFloorPlans: false,
      showAnalytics: false,
      showEducationalContent: true,
      guidedMode: true,
      showVisuals: false,
      comparePackages: false,
      showVelocity: false,
      priorityIndicators: false
    }
  },
  
  LISA: {
    id: 'lisa',
    name: 'Lisa Chen',
    role: 'Remodeling Contractor',
    title: 'Remodeling Contractor',
    company: 'Chen Design Build',
    description: 'High-end residential remodels',
    email: 'lisa.chen@chendesignbuild.com',
    customerGroup: CUSTOMER_GROUPS.TRADE_PROFESSIONAL,
    avatar: '/images/avatars/lisa.jpg',
    defaultRoute: '/pages/builder.html?type=package',
    
    attributes: {
      package_tier: 'better',
      room_category: 'bathroom',
      customer_tier: 'Trade-Professional',
      business_type: 'remodeling_contractor',
      project_scale: 'medium_volume',
      primary_service: 'remodeling',
      buying_behavior: 'project_based'
    },
    
    features: {
      templates: false,
      bomGeneration: false,
      phaseOrdering: false,
      repeatOrdering: false,
      projectWizard: false,
      packageBuilder: true,
      customization: true,
      visualization: true,
      quoteGeneration: true,
      deckBuilder: false,
      restockDashboard: false
    },
    
    preferences: {
      defaultView: 'packages',
      showFloorPlans: false,
      showAnalytics: false,
      showEducationalContent: false,
      guidedMode: false,
      showVisuals: true,
      comparePackages: true,
      showVelocity: false,
      priorityIndicators: false
    }
  },
  
  DAVID: {
    id: 'david',
    name: 'David Thompson',
    role: 'Pro Homeowner',
    title: 'Pro Homeowner',
    company: null,
    description: 'DIY enthusiast building a deck',
    email: 'david.thompson@email.com',
    customerGroup: CUSTOMER_GROUPS.RETAIL_REGISTERED,
    avatar: '/images/avatars/david.jpg',
    defaultRoute: '/pages/builder.html?type=deck',
    
    attributes: {
      deck_compatible: true,
      deck_shape: 'rectangular',
      deck_material_type: 'composite',
      customer_tier: 'Retail-Registered',
      business_type: 'diy_homeowner',
      project_scale: 'single_project',
      primary_service: 'diy',
      buying_behavior: 'single_items'
    },
    
    features: {
      templates: false,
      bomGeneration: false,
      phaseOrdering: false,
      repeatOrdering: false,
      projectWizard: false,
      packageBuilder: false,
      deckBuilder: true,
      educationalContent: true,
      diyGuidance: true,
      productRecommendations: true,
      restockDashboard: false
    },
    
    preferences: {
      defaultView: 'deck_builder',
      showFloorPlans: false,
      showAnalytics: false,
      showEducationalContent: true,
      guidedMode: true,
      showVisuals: true,
      comparePackages: false,
      showVelocity: false,
      priorityIndicators: false
    }
  },
  
  KEVIN: {
    id: 'kevin',
    name: 'Kevin Rodriguez',
    role: 'Store Manager',
    title: 'Store Manager',
    company: 'BuildRight Store #247',
    description: 'Managing inventory for pro contractor store',
    email: 'kevin.rodriguez@buildright.com',
    customerGroup: CUSTOMER_GROUPS.WHOLESALE_RESELLER,
    avatar: '/images/avatars/kevin.jpg',
    defaultRoute: '/pages/dashboard.html?view=restock',
    
    attributes: {
      store_velocity_category: 'high_volume',
      restock_priority: 'high',
      customer_tier: 'Wholesale-Reseller',
      business_type: 'retail_store',
      project_scale: 'high_volume',
      primary_service: 'retail',
      buying_behavior: 'bulk_orders'
    },
    
    features: {
      templates: false,
      bomGeneration: false,
      phaseOrdering: false,
      repeatOrdering: false,
      projectWizard: false,
      packageBuilder: false,
      deckBuilder: false,
      restockDashboard: true,
      velocityAnalysis: true,
      smartSuggestions: true,
      bulkOrdering: true
    },
    
    preferences: {
      defaultView: 'restock',
      showFloorPlans: false,
      showAnalytics: true,
      showEducationalContent: false,
      guidedMode: false,
      showVisuals: false,
      comparePackages: false,
      showVelocity: true,
      priorityIndicators: true
    }
  }
};

/**
 * Get persona by ID
 * @param {string} personaId - Persona ID (e.g., 'sarah', 'marcus')
 * @returns {Object|null} Persona object or null if not found
 */
export function getPersona(personaId) {
  return Object.values(PERSONAS).find(p => p.id === personaId) || null;
}

/**
 * Get all personas as array
 * @returns {Array} Array of all persona objects
 */
export function getAllPersonas() {
  return Object.values(PERSONAS);
}

/**
 * Get personas by customer group
 * @param {string} customerGroup - Customer group ID
 * @returns {Array} Array of personas in the customer group
 */
export function getPersonasByGroup(customerGroup) {
  return Object.values(PERSONAS).filter(p => p.customerGroup === customerGroup);
}

/**
 * Check if persona has feature
 * @param {string} personaId - Persona ID
 * @param {string} feature - Feature key
 * @returns {boolean} True if persona has feature enabled
 */
export function hasFeature(personaId, feature) {
  const persona = getPersona(personaId);
  return persona?.features?.[feature] === true;
}

/**
 * Get persona preference
 * @param {string} personaId - Persona ID
 * @param {string} prefKey - Preference key
 * @returns {*} Preference value or undefined
 */
export function getPreference(personaId, prefKey) {
  const persona = getPersona(personaId);
  return persona?.preferences?.[prefKey];
}

/**
 * Get persona attributes (for ACO policy filtering)
 * @param {string} personaId - Persona ID
 * @returns {Object} Persona attributes object
 */
export function getPersonaAttributes(personaId) {
  const persona = getPersona(personaId);
  return persona?.attributes || {};
}

/**
 * Get customer group for persona
 * @param {string} personaId - Persona ID
 * @returns {string|null} Customer group ID
 */
export function getCustomerGroup(personaId) {
  const persona = getPersona(personaId);
  return persona?.customerGroup || null;
}

/**
 * Get default route for persona
 * @param {string} personaId - Persona ID
 * @returns {string} Default route path
 */
export function getDefaultRoute(personaId) {
  const persona = getPersona(personaId);
  return persona?.defaultRoute || '/pages/dashboard.html';
}

/**
 * Validate persona ID
 * @param {string} personaId - Persona ID to validate
 * @returns {boolean} True if persona ID is valid
 */
export function isValidPersona(personaId) {
  return getPersona(personaId) !== null;
}

