#!/bin/bash

##
# Sync Product Images from buildright-data to buildright-eds
# 
# Usage: npm run sync:images
#
# This script copies product images from buildright-data (the source of truth)
# to the frontend. Images are generated by commerce-demo-generator during
# datapack generation.
##

set -e

# Resolve paths
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

# Try to find buildright-data repository (sibling directory)
DATA_REPO=""
if [ -d "$PROJECT_ROOT/../buildright-data" ]; then
  DATA_REPO="$( cd "$PROJECT_ROOT/../buildright-data" && pwd )"
fi

SOURCE_DIR="${DATA_REPO}/media/images/products"
DEST_DIR="${PROJECT_ROOT}/images/products"

# Validate source directory exists
if [ -z "$DATA_REPO" ] || [ ! -d "$SOURCE_DIR" ]; then
  echo ""
  echo "✖ Error: buildright-data/media/images/products not found"
  echo ""
  echo "Expected location:"
  echo "  $PROJECT_ROOT/../buildright-data/media/images/products"
  echo ""
  echo "Please ensure:"
  echo "  1. buildright-data repository is cloned"
  echo "  2. Images have been generated:"
  echo "     cd ../commerce-demo-generator && npm run generate:commerce"
  echo ""
  exit 1
fi

# Validate destination directory exists
if [ ! -d "$DEST_DIR" ]; then
  echo ""
  echo "✖ Error: Destination directory not found"
  echo "  $DEST_DIR"
  echo ""
  exit 1
fi

# Count images
SOURCE_COUNT=$(find "$SOURCE_DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) 2>/dev/null | wc -l | tr -d ' ')
BEFORE_COUNT=$(find "$DEST_DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) 2>/dev/null | wc -l | tr -d ' ')

echo ""
echo "📦 Syncing product images..."
echo ""
echo "Source:      $SOURCE_DIR"
echo "Destination: $DEST_DIR"
echo ""
echo "Images in buildright-data: $SOURCE_COUNT"
echo "Images in buildright-eds:  $BEFORE_COUNT"
echo ""

if [ "$SOURCE_COUNT" -eq 0 ]; then
  echo "⚠  No images found in buildright-data"
  echo ""
  echo "Run the generator first:"
  echo "  cd ../commerce-demo-generator"
  echo "  npm run generate:commerce"
  echo ""
  exit 0
fi

# Sync images using rsync
rsync -a --delete \
  --include="*.jpg" \
  --include="*.jpeg" \
  --include="*.png" \
  --exclude="*" \
  "$SOURCE_DIR/" "$DEST_DIR/"

# Count after sync
AFTER_COUNT=$(find "$DEST_DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) 2>/dev/null | wc -l | tr -d ' ')

echo "✔ Sync complete"
echo ""
echo "Images synced: $AFTER_COUNT"

if [ $AFTER_COUNT -gt $BEFORE_COUNT ]; then
  NEW_COUNT=$((AFTER_COUNT - BEFORE_COUNT))
  echo "Added: $NEW_COUNT"
elif [ $AFTER_COUNT -lt $BEFORE_COUNT ]; then
  REMOVED_COUNT=$((BEFORE_COUNT - AFTER_COUNT))
  echo "Removed: $REMOVED_COUNT"
else
  echo "No changes"
fi

echo ""
