#!/bin/bash

##
# Sync Product Images from buildright-data to buildright-eds
# 
# Usage: ./scripts/sync-product-images.sh
#
# This script copies product images from buildright-data (the source of truth)
# to the frontend. Images are generated by commerce-demo-generator during
# datapack generation.
##

set -e

# Define paths
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
DATA_REPO_IMAGES="$( cd "$PROJECT_ROOT/../../buildright-data/media/images/products" 2>/dev/null && pwd || echo "" )"
DEST_DIR="${PROJECT_ROOT}/images/products"

echo "🖼️  Product Image Sync"
echo ""

# Validate source directory exists
if [ -z "$DATA_REPO_IMAGES" ] || [ ! -d "$DATA_REPO_IMAGES" ]; then
  echo "❌ Error: buildright-data/media/images/products not found"
  echo ""
  echo "Expected path: ../../buildright-data/media/images/products"
  echo ""
  echo "Please ensure:"
  echo "  1. buildright-data repository is cloned"
  echo "  2. Images have been generated: cd commerce-demo-generator && npm run generate:commerce"
  exit 1
fi

# Validate destination directory exists
if [ ! -d "$DEST_DIR" ]; then
  echo "❌ Error: Destination directory not found: $DEST_DIR"
  exit 1
fi

# Count images
SOURCE_COUNT=$(find "$DATA_REPO_IMAGES" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | wc -l | tr -d ' ')
BEFORE_COUNT=$(find "$DEST_DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | wc -l | tr -d ' ')

echo "Source: $DATA_REPO_IMAGES"
echo "Destination: $DEST_DIR"
echo ""
echo "Images in buildright-data: $SOURCE_COUNT"
echo "Images in buildright-eds (before): $BEFORE_COUNT"
echo ""

if [ "$SOURCE_COUNT" -eq 0 ]; then
  echo "⚠️  No images found in buildright-data"
  echo ""
  echo "Run the generator first:"
  echo "  cd ../commerce-demo-generator"
  echo "  npm run generate:commerce"
  exit 0
fi

# Sync images (rsync is more efficient than cp)
echo "📦 Syncing images..."
echo ""

rsync -av --delete \
  --include="*.jpg" \
  --include="*.jpeg" \
  --include="*.png" \
  --exclude="*" \
  "$DATA_REPO_IMAGES/" "$DEST_DIR/"

# Count after sync
AFTER_COUNT=$(find "$DEST_DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | wc -l | tr -d ' ')

echo ""
echo "✅ Sync complete!"
echo ""
echo "Images in buildright-eds (after): $AFTER_COUNT"

if [ $AFTER_COUNT -gt $BEFORE_COUNT ]; then
  echo "New images added: $((AFTER_COUNT - BEFORE_COUNT))"
elif [ $AFTER_COUNT -lt $BEFORE_COUNT ]; then
  echo "Images removed: $((BEFORE_COUNT - AFTER_COUNT))"
else
  echo "No changes (all images up-to-date)"
fi

echo ""
echo "ℹ️  Note: Backend uses convention: /images/products/{SKU}.jpeg"
echo "   Images are automatically extracted during datapack generation"
echo ""
